# Run windows builds on appveyor.com

version: "Build #{build}"

environment:
 PYTHON: C:\Python36

install:
 # Path setup
 - set PATH=%PYTHON%;%PYTHON%\Scripts;%APPVEYOR_BUILD_FOLDER%;%PATH%

 # Install dependencies
 - python -m pip install --upgrade pip
 - pip install -r requirements.txt

 # Log versions
 - python --version
 - pip list --format=columns

 # Download libusb
 - appveyor DownloadFile http://jaist.dl.sourceforge.net/project/libusb-win32/libusb-win32-releases/1.2.6.0/libusb-win32-bin-1.2.6.0.zip
 - 7z x libusb-win32-bin-1.2.6.0.zip
 - move libusb-win32-bin-1.2.6.0\bin\x86\libusb0_x86.dll libusb0.dll

build: off

after_test:
 # Run pyinstaller
 - python -OO -m PyInstaller pmca-console.spec
 - python -OO -m PyInstaller pmca-gui.spec

artifacts:
 - path: dist\*

deploy:
 # Deploy tagged releases
 - provider: GitHub
   auth_token: {secure: oojQVGlq4+lrv8NZ2LlNpsMMavvFEwgUKGgqZJ+TnoVV8XwqrbJnuAyvI2AHcCYu}
   artifact: /.*/
   on: {appveyor_repo_tag: true}
